# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 815ffe1bd287de811633a2cfdcf901fafdc6b09adac212f2694823b921390d6a09dcc682780d1095855496e1ca44cd9d473072b03c46f593a51fa3e07bd69d21
  mandrill_key: qCc_ZE43RIILB9vAEKeS_g
  mandrill_username: app33127969@heroku.com

test:
  secret_key_base: 2b469992e2717344f54c32ba694a1216c5b78a5acd02c26c05bcbff06ac74a011a03d06ae9890e341d4cdda333b5ea9b19a1fa5d42bb4dba8aeb52ddb81a4542

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
